#!/bin/bash

# made selenium to work for various browsers as follows:
# - for firefox add the line below to file
#  /usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-0.2.1/lib/selenium-webdriver.rb 
#  Selenium::WebDriver::Firefox::Binary.path="/Applications/Firefox.app/Contents/MacOS/firefox-bin"
# - for chrome download the chrome driver from
#   http://code.google.com/p/selenium/downloads/list
#   and put it somewhere in the path with exec permissions

# rake jasmine:ci JASMINE_BROWSER=firefox
rake jasmine:ci JASMINE_BROWSER=chrome
